# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives
  About: about


social:
  email: magicalne@gmail.com
  twitter: magicalne
  github: magicalne
  googleplus: magicalne

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: #disqus _shortname
google_analytics: #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code

less:
  paths:
    - source/css
  compress:
    true
